<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>d_repo</RootNamespace>
        <AssemblyName>d-Space</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <ScssFiles Include="wwwroot\site.scss" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Pages\Details\" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
    </ItemGroup>

    <Target Name="CompileScss" BeforeTargets="Build" Inputs="@(ScssFiles)" Outputs="@(ScssFiles->'wwwroot\\%(Filename).css')">
        <Message Text="Kompiluji SCSS soubory..." Importance="high" />
        <Exec Command="npx sass --no-source-map &quot;%(ScssFiles.Identity)&quot; &quot;wwwroot\%(ScssFiles.Filename).css&quot;" />
    </Target>
</Project>
