<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <ScssFiles Include="wwwroot\scss\site.scss" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Pages\Details\" />
    </ItemGroup>

    <Target Name="CompileScss"
            BeforeTargets="Build"
            Inputs="@(ScssFiles)"
            Outputs="@(ScssFiles->'wwwroot\\css\\%(Filename).css')">
        <Message Text="Kompiluji SCSS soubory..." Importance="high" />
        <Exec Command="npx sass --no-source-map &quot;%(ScssFiles.Identity)&quot; &quot;wwwroot\css\%(ScssFiles.Filename).css&quot;" />
    </Target>
</Project>
