<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>d_base</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ScssFiles Include="wwwroot\site.scss"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="wwwroot\js\"/>
    </ItemGroup>
    <ItemGroup>
        <Content Include="../assets/**/*"
                 Link="assets/%(RecursiveDir)%(Filename)%(Extension)"
                 CopyToOutputDirectory="PreserveNewest"
                 CopyToPublishDirectory="PreserveNewest" />
    </ItemGroup>

    <Target Name="CompileScss" BeforeTargets="Build">
        <Exec Command="npx sass --no-source-map &quot;wwwroot\site.scss&quot; &quot;wwwroot\site.css&quot;" />
    </Target>

</Project>
